<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <Configurations>Debug_All;Debug;Release</Configurations>
    <ApplicationIcon>DD_BIM_ICON.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <!-- Fallback für Architektur (wenn $(PlatformTarget) leer ist) -->
  <PropertyGroup>
    <InteropArch>$(PlatformTarget)</InteropArch>
    <InteropArch Condition="'$(InteropArch)' == ''">x64</InteropArch>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BIMGISInteropLibs\BIMGISInteropLibs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DD_BIM_ICON.ico" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>  <ItemGroup>
    <PackageReference Include="GDAL.Native" />
  </ItemGroup>

</Project>