// <auto-generated>
//     Diese Datei wurde automatisch mit T4 generiert.
//     Änderungen werden beim nächsten Generieren überschrieben.
// </auto-generated>

using BimGisCad.Representation.Geometry;
using BimGisCad.Representation.Geometry.Elementary;
using BIMGISInteropLibs.IFC;
using BIMGISInteropLibs.IFC.Ifc4;
using BIMGISInteropLibs.IfcTerrain;
using Xbim.Ifc4.GeometricConstraintResource;
using Xbim.Ifc4.GeometryResource;
using Xbim.Ifc4.RepresentationResource;

namespace UnitTest;

using LogWriter = BIMGISInteropLibs.Logging.LogWriterIfcTerrain; //to set log messages
public class FunctionTestIfc4
{
    [Theory]
    [MemberData(nameof(LoGeoRefRotationTestCases))]
    public void RotationTest(BIMGISInteropLibs.IFC.LoGeoRef loGeoRef, double rotation, double expectedX, double expectedY) //expected values for RefDirection
    {
        Axis2Placement3D sitePlacement = Axis2Placement3D.Create(Direction3.UnitZ, rotation);
        Config config = new Config()
        {
            projectName = "Rotation Test",
        };
        LogWriter.initLogger(config);
        var model = InitModel.Create(config.projectName, config.editorsFamilyName,
                config.editorsGivenName, config.editorsOrganisationName, out var project);

        switch (loGeoRef)
        {
            
        case BIMGISInteropLibs.IFC.LoGeoRef.LoGeoRef50:
                {
                    IfcGeometricRepresentationContext geomRepContext = BIMGISInteropLibs.IFC.Ifc4.LoGeoRef.Level50.Create(model, sitePlacement, config);
                    if (geomRepContext.TrueNorth != null)
                    {
                        Assert.Equal(1.0, geomRepContext.TrueNorth.X, FunctionTestMain.digits); //If set, expecting TrueNorth as default
                        Assert.Equal(0.0, geomRepContext.TrueNorth.Y, FunctionTestMain.digits);
                    }
                    if (geomRepContext.WorldCoordinateSystem is IfcAxis2Placement3D { RefDirection: IfcDirection dir })
                    {
                        Assert.Equal(1.0, dir.X, FunctionTestMain.digits); //If set, expecting RefDirection as default
                        Assert.Equal(0.0, dir.Y, FunctionTestMain.digits);
                    }
                    var mapConversion = model.Instances.OfType<IfcMapConversion>().FirstOrDefault(x => x.SourceCRS.Equals(geomRepContext));
                    Assert.NotNull(mapConversion);
                    Assert.NotNull(mapConversion.XAxisAbscissa);
                    Assert.NotNull(mapConversion.XAxisOrdinate);
                    Assert.Equal(expectedX, mapConversion.XAxisAbscissa.Value, FunctionTestMain.digits);
                    Assert.Equal(expectedY, mapConversion.XAxisOrdinate.Value, FunctionTestMain.digits);
                }
                break;
       

            //Level 40
            case BIMGISInteropLibs.IFC.LoGeoRef.LoGeoRef40:
                {     
                    IfcGeometricRepresentationContext geomRepContext = BIMGISInteropLibs.IFC.Ifc4.LoGeoRef.Level40.Create(model, sitePlacement);
                    Assert.Equal(-expectedY, geomRepContext.TrueNorth.X, FunctionTestMain.digits); //Expecting RefDirection as default
                    Assert.Equal(expectedX, geomRepContext.TrueNorth.Y, FunctionTestMain.digits);
                    if (geomRepContext.WorldCoordinateSystem is IfcAxis2Placement3D { RefDirection: IfcDirection dir })
                    {
                        Assert.Equal(1.0, dir.X, FunctionTestMain.digits); //If set Expecting RefDirection as default
                        Assert.Equal(0.0, dir.Y, FunctionTestMain.digits);
                    }
                }
                break;

            //Level 30
            default:
                var site = Site.Create(model, "Rotation Test Site", loGeoRef, sitePlacement);
                {
                    if (site.ObjectPlacement is IfcLocalPlacement { RelativePlacement: IfcAxis2Placement3D { RefDirection: IfcDirection dir } })
                    {
                        Assert.Equal(expectedX, dir.X, FunctionTestMain.digits);
                        Assert.Equal(expectedY, dir.Y, FunctionTestMain.digits);
                    }
                    else
                    {
                        Assert.True(false, "ObjectPlacement/RelativePlacement/RefDirection type mismatch");
                    }
                }
                break;
        }
    }
    public static IEnumerable<object[]> LoGeoRefRotationTestCases()
    {
        foreach (var loGeoRef in Enum.GetValues(typeof(BIMGISInteropLibs.IFC.LoGeoRef)))
        {
            foreach (var testCase in FunctionTestMain.RotationTestCases())
            {
                yield return new object[] { loGeoRef, testCase[0], testCase[1], testCase[2] };
            }
        }
    }
}
