// <auto-generated>
//     Diese Datei wurde automatisch mit T4 generiert.
//     Änderungen werden beim nächsten Generieren überschrieben.
// </auto-generated>

using BimGisCad.Representation.Geometry;
using BimGisCad.Representation.Geometry.Elementary;
using BIMGISInteropLibs.IFC;
using BIMGISInteropLibs.IFC.Ifc2x3;
using BIMGISInteropLibs.IfcTerrain;
using Xbim.Ifc2x3.GeometricConstraintResource;
using Xbim.Ifc2x3.GeometryResource;
using Xbim.Ifc2x3.RepresentationResource;

namespace UnitTest;

using LogWriter = BIMGISInteropLibs.Logging.LogWriterIfcTerrain; //to set log messages
public class FunctionTestIfc2x3
{
    [Theory]
    [MemberData(nameof(LoGeoRefRotationTestCases))]
    public void RotationTest(BIMGISInteropLibs.IFC.LoGeoRef loGeoRef, double rotation, double expectedX, double expectedY) //expected values for RefDirection
    {
        Axis2Placement3D sitePlacement = Axis2Placement3D.Create(Direction3.UnitZ, rotation);
        Config config = new Config()
        {
            projectName = "Rotation Test",
        };
        LogWriter.initLogger(config);
        var model = InitModel.Create(config.projectName, config.editorsFamilyName,
                config.editorsGivenName, config.editorsOrganisationName, out var project);

        switch (loGeoRef)
        {
            

            //Level 40
            case BIMGISInteropLibs.IFC.LoGeoRef.LoGeoRef40:
                {     
                    IfcGeometricRepresentationContext geomRepContext = BIMGISInteropLibs.IFC.Ifc2x3.LoGeoRef.Level40.Create(model, sitePlacement);
                    Assert.Equal(-expectedY, geomRepContext.TrueNorth.X, FunctionTestHelper.digits); //Expecting RefDirection as default
                    Assert.Equal(expectedX, geomRepContext.TrueNorth.Y, FunctionTestHelper.digits);
                    if (geomRepContext.WorldCoordinateSystem is IfcAxis2Placement3D { RefDirection: IfcDirection dir })
                    {
                        Assert.Equal(1.0, dir.X, FunctionTestHelper.digits); //If set Expecting RefDirection as default
                        Assert.Equal(0.0, dir.Y, FunctionTestHelper.digits);
                    }
                }
                break;

            //Level 30
            default:
                var site = Site.Create(model, "Rotation Test Site", loGeoRef, sitePlacement);
                {
                    if (site.ObjectPlacement is IfcLocalPlacement { RelativePlacement: IfcAxis2Placement3D { RefDirection: IfcDirection dir } })
                    {
                        Assert.Equal(expectedX, dir.X, FunctionTestHelper.digits);
                        Assert.Equal(expectedY, dir.Y, FunctionTestHelper.digits);
                    }
                    else
                    {
                        Assert.True(false, "ObjectPlacement/RelativePlacement/RefDirection type mismatch");
                    }
                }
                break;
        }
    }
    public static IEnumerable<object[]> LoGeoRefRotationTestCases()
    {
        foreach (var loGeoRef in Enum.GetValues(typeof(BIMGISInteropLibs.IFC.LoGeoRef)))
        {
            foreach (var testCase in FunctionTestHelper.RotationTestCases())
            {
                yield return new object[] { loGeoRef, testCase[0], testCase[1], testCase[2] };
            }
        }
    }
}
