//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFCGeoRefCheckerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFCGeoRefCheckerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check selected file ähnelt.
        /// </summary>
        internal static string CHECK_SELECTED_FILE {
            get {
                return ResourceManager.GetString("CHECK_SELECTED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file(s) checked ähnelt.
        /// </summary>
        internal static string FILES_CHECKED_FORMAT {
            get {
                return ResourceManager.GetString("FILES_CHECKED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file(s) loaded ähnelt.
        /// </summary>
        internal static string FILES_LOADED_FORMAT {
            get {
                return ResourceManager.GetString("FILES_LOADED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input IFC-Files ähnelt.
        /// </summary>
        internal static string INPUT_IFC_FILES {
            get {
                return ResourceManager.GetString("INPUT_IFC_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select language : ähnelt.
        /// </summary>
        internal static string LANGUAGE_LABEL {
            get {
                return ResourceManager.GetString("LANGUAGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load IFC-Files ähnelt.
        /// </summary>
        internal static string LOAD_IFC_FILES {
            get {
                return ResourceManager.GetString("LOAD_IFC_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loaded IFC-Files ähnelt.
        /// </summary>
        internal static string LOADED_IFC_FILES {
            get {
                return ResourceManager.GetString("LOADED_IFC_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log output ähnelt.
        /// </summary>
        internal static string LOG_OUTPUT {
            get {
                return ResourceManager.GetString("LOG_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose path! ähnelt.
        /// </summary>
        internal static string PLEASE_CHOOSE_PATH {
            get {
                return ResourceManager.GetString("PLEASE_CHOOSE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFCGeoRefChecker protocoll for file ähnelt.
        /// </summary>
        internal static string PROTOCOL_HEADER {
            get {
                return ResourceManager.GetString("PROTOCOL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set working directory ähnelt.
        /// </summary>
        internal static string SET_WORKING_DIRECTORY {
            get {
                return ResourceManager.GetString("SET_WORKING_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show protocol ähnelt.
        /// </summary>
        internal static string SHOW_PROTOCOL {
            get {
                return ResourceManager.GetString("SHOW_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        internal static string STATUS_LABEL {
            get {
                return ResourceManager.GetString("STATUS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status report ähnelt.
        /// </summary>
        internal static string STATUS_REPORT {
            get {
                return ResourceManager.GetString("STATUS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working directory ähnelt.
        /// </summary>
        internal static string WORKING_DIRECTORY_LABEL {
            get {
                return ResourceManager.GetString("WORKING_DIRECTORY_LABEL", resourceCulture);
            }
        }
    }
}
