//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City2RVT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("City2RVT.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Wpf_CityGML_settingsButton_bt_applyGeoref {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsButton_bt_applyGeoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist translation.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of codes into its meaning.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_lbl8 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use Codelist for translation.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_lbl9 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_Bt_browse {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_Bt_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File settings.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_lbl6 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of coordinates:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_lbl7 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZ / NEH (Northings, Eastings, Height).
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_rb_XYZ {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_rb_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YXZ / ENH (Eastings, Northings, Height.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_rb_YXZ {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_rb_YXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit URL.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_bt_editUrl {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_bt_editUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save response to.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_check_saveResponse {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_check_saveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl1 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl2 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl3 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl4 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extent:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl5 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_Rb_custom {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_Rb_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Site location.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_rb_site {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_rb_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityGML file.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_rb_file {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_rb_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS server.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_rb_server {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_rb_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Wpf_CityGML_settingsWindowTitle {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsWindowTitle", resourceCulture);
            }
        }
    }
}
