//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City2RVT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("City2RVT.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string DataCatalogEditorWindow_id1 {
            get {
                return ResourceManager.GetString("DataCatalogEditorWindow_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string DataCatalogEditorWindow_id2 {
            get {
                return ResourceManager.GetString("DataCatalogEditorWindow_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query External Data Catalog.
        /// </summary>
        internal static string findSubjectResultForm {
            get {
                return ResourceManager.GetString("findSubjectResultForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string findSubjectResultForm_closeBtn {
            get {
                return ResourceManager.GetString("findSubjectResultForm_closeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text for subjects.
        /// </summary>
        internal static string findSubjectResultForm_id1 {
            get {
                return ResourceManager.GetString("findSubjectResultForm_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string findSubjectResultForm_queryBtn {
            get {
                return ResourceManager.GetString("findSubjectResultForm_queryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set selected object.
        /// </summary>
        internal static string findSubjectResultForm_setObjectBtn {
            get {
                return ResourceManager.GetString("findSubjectResultForm_setObjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City2RVT IfcExport.
        /// </summary>
        internal static string IfcExportDialog {
            get {
                return ResourceManager.GetString("IfcExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string IfcExportDialog_cancelBtn {
            get {
                return ResourceManager.GetString("IfcExportDialog_cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        internal static string IfcExportDialog_exportBtn {
            get {
                return ResourceManager.GetString("IfcExportDialog_exportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File.
        /// </summary>
        internal static string IfcExportDialog_FileLabel {
            get {
                return ResourceManager.GetString("IfcExportDialog_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfcGeographicElement.
        /// </summary>
        internal static string IfcExportDialog_geogElemRadioBtn {
            get {
                return ResourceManager.GetString("IfcExportDialog_geogElemRadioBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Alkis / XPlanung Export Type.
        /// </summary>
        internal static string IfcExportDialog_id1 {
            get {
                return ResourceManager.GetString("IfcExportDialog_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string IfcExportDialog_saveAsButton {
            get {
                return ResourceManager.GetString("IfcExportDialog_saveAsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfcSite.
        /// </summary>
        internal static string IfcExportDialog_siteRadioBtn {
            get {
                return ResourceManager.GetString("IfcExportDialog_siteRadioBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string ImportDialogAlkis_browseButton {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string ImportDialogAlkis_cancelButton {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ImportDialogAlkis_clearSelectionBtn {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_clearSelectionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ImportDialogAlkis_FileLabel {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers to Import.
        /// </summary>
        internal static string ImportDialogAlkis_id1 {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drape on Terrain.
        /// </summary>
        internal static string ImportDialogAlkis_id2 {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drape objects on imported terrain.
        /// </summary>
        internal static string ImportDialogAlkis_id3 {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        internal static string ImportDialogAlkis_importButton {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_importButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ImportDialogAlkis_selectAllBtn {
            get {
                return ResourceManager.GetString("ImportDialogAlkis_selectAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string ImportXPlanDialog_browseButton {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string ImportXPlanDialog_cancelButton {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ImportXPlanDialog_clearSelectionBtn {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_clearSelectionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ImportXPlanDialog_FileLabel {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers to Import.
        /// </summary>
        internal static string ImportXPlanDialog_id1 {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drape on Terrain.
        /// </summary>
        internal static string ImportXPlanDialog_id2 {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drape objects on imported terrain.
        /// </summary>
        internal static string ImportXPlanDialog_id3 {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        internal static string ImportXPlanDialog_importButton {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_importButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ImportXPlanDialog_selectAllBtn {
            get {
                return ResourceManager.GetString("ImportXPlanDialog_selectAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayerSelector.
        /// </summary>
        internal static string LayerSelector {
            get {
                return ResourceManager.GetString("LayerSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        internal static string LayerSelector_apply {
            get {
                return ResourceManager.GetString("LayerSelector_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string LayerSelector_cancel {
            get {
                return ResourceManager.GetString("LayerSelector_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        internal static string LayerSelector_selectAll {
            get {
                return ResourceManager.GetString("LayerSelector_selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect all.
        /// </summary>
        internal static string LayerSelector_unSelectAll {
            get {
                return ResourceManager.GetString("LayerSelector_unSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to External Data Catalog.
        /// </summary>
        internal static string LoginScreen_id1 {
            get {
                return ResourceManager.GetString("LoginScreen_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-Url.
        /// </summary>
        internal static string LoginScreen_id2 {
            get {
                return ResourceManager.GetString("LoginScreen_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginScreen_id3 {
            get {
                return ResourceManager.GetString("LoginScreen_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginScreen_id4 {
            get {
                return ResourceManager.GetString("LoginScreen_id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string LoginScreen_id5 {
            get {
                return ResourceManager.GetString("LoginScreen_id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes for Object.
        /// </summary>
        internal static string PropertyWindow {
            get {
                return ResourceManager.GetString("PropertyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save and close.
        /// </summary>
        internal static string PropertyWindow_id1 {
            get {
                return ResourceManager.GetString("PropertyWindow_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string PropertyWindow_id2 {
            get {
                return ResourceManager.GetString("PropertyWindow_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Wpf_CityGML_settings {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Wpf_CityGML_settingsButton_bt_applyGeoref {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsButton_bt_applyGeoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist translation.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of codes into its meaning.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_lbl8 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use Codelist for translation.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_code_lbl9 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_code_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_Bt_browse {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_Bt_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File settings.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_lbl6 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of coordinates:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_lbl7 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZ / NEH (Northings, Eastings, Height).
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_rb_XYZ {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_rb_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YXZ / ENH (Eastings, Northings, Height.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_prop_rb_YXZ {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_prop_rb_YXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit URL.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_bt_editUrl {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_bt_editUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save response to.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_check_saveResponse {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_check_saveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl1 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl2 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl3 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl4 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extent:.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_lbl5 {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_Rb_custom {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_Rb_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Site location.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_server_rb_site {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_server_rb_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_header {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityGML file.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_rb_file {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_rb_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS server.
        /// </summary>
        internal static string Wpf_CityGML_settingsGroupBox_gr_source_rb_server {
            get {
                return ResourceManager.GetString("Wpf_CityGML_settingsGroupBox_gr_source_rb_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        internal static string Wpf_CreateMetaJSON {
            get {
                return ResourceManager.GetString("Wpf_CreateMetaJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Wpf_CreateMetaJSON_Btn_Start {
            get {
                return ResourceManager.GetString("Wpf_CreateMetaJSON_Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme.
        /// </summary>
        internal static string Wpf_CreateMetaJSON_Cb_Theme {
            get {
                return ResourceManager.GetString("Wpf_CreateMetaJSON_Cb_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georeferencing.
        /// </summary>
        internal static string Wpf_GeoRef_Form {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Wpf_GeoRef_Form_bt_applyGeoref {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_bt_applyGeoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Wpf_GeoRef_Form_bt_quit {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_bt_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address.
        /// </summary>
        internal static string Wpf_GeoRef_Form_group10 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_group10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address lines:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id1 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected coordinates.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id10 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastings [m]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id11 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northings [m]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id12 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid North [°]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id13 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id14 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSG-Code (CRS):.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id15 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id16 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthometric Height [m]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id17 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Datum:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id18 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM transformation.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id19 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id2 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id20 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id3 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id4 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id5 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic site coordinates.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id6 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude [°]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id7 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude [°].
        /// </summary>
        internal static string Wpf_GeoRef_Form_id8 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True North [°]:.
        /// </summary>
        internal static string Wpf_GeoRef_Form_id9 {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_id9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deg.
        /// </summary>
        internal static string Wpf_GeoRef_Form_rb_deg {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_rb_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        internal static string Wpf_GeoRef_Form_rb_dms {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_rb_dms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection (UTM) to Site (LatLon).
        /// </summary>
        internal static string Wpf_GeoRef_Form_rb_projToSite {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_rb_projToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site (LatLon) to Projection (UTM).
        /// </summary>
        internal static string Wpf_GeoRef_Form_rb_siteToProj {
            get {
                return ResourceManager.GetString("Wpf_GeoRef_Form_rb_siteToProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select layer.
        /// </summary>
        internal static string Wpf_showLayer {
            get {
                return ResourceManager.GetString("Wpf_showLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Wpf_showLayer_btn_choose {
            get {
                return ResourceManager.GetString("Wpf_showLayer_btn_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Wpf_showLayer_btn_exportjson {
            get {
                return ResourceManager.GetString("Wpf_showLayer_btn_exportjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Wpf_showLayer_btn_gml {
            get {
                return ResourceManager.GetString("Wpf_showLayer_btn_gml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Wpf_showLayer_btn_metajson {
            get {
                return ResourceManager.GetString("Wpf_showLayer_btn_metajson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GML.
        /// </summary>
        internal static string Wpf_showLayer_id1 {
            get {
                return ResourceManager.GetString("Wpf_showLayer_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta JSON.
        /// </summary>
        internal static string Wpf_showLayer_id2 {
            get {
                return ResourceManager.GetString("Wpf_showLayer_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON.
        /// </summary>
        internal static string Wpf_showLayer_id3 {
            get {
                return ResourceManager.GetString("Wpf_showLayer_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to IFC.
        /// </summary>
        internal static string Wpf_XPlan2IFC {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export surfaces as IfcSite.
        /// </summary>
        internal static string Wpf_XPlan2IFC_checkboxAsSite {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_checkboxAsSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export surfaces as IfcSpace.
        /// </summary>
        internal static string Wpf_XPlan2IFC_checkboxAsSpace {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_checkboxAsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id1 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id2 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer to be exported.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id3 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id4 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to IFC.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id5 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Wpf_XPlan2IFC_id6 {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string Wpf_XPlan2IFC_rb_selectAll {
            get {
                return ResourceManager.GetString("Wpf_XPlan2IFC_rb_selectAll", resourceCulture);
            }
        }
    }
}
