//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City2RVT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_MetaJSONs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_MetaJSONs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("City2RVT.Resource_MetaJSONs", typeof(Resource_MetaJSONs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;AAA&quot;,
        ///    &quot;meta&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;AA_Aktivitaet&quot;,
        ///            &quot;properties&quot;: [
        ///                {
        ///                    &quot;name&quot;: &quot;metaDataProperty&quot;,
        ///                    &quot;dataType&quot;: &quot;MetaDataPropertyType&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;description&quot;,
        ///                    &quot;dataType&quot;: &quot;StringOrRefType&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;descriptionReference&quot;,
        ///                    &quot;dataType&quot;: &quot;ReferenceType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aaa {
            get {
                return ResourceManager.GetString("aaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;AAA&quot;,
        ///    &quot;meta&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;AX_Bahnverkehr&quot;,
        ///            &quot;properties&quot;: [
        ///                {
        ///                    &quot;name&quot;: &quot;metaDataProperty&quot;,
        ///                    &quot;dataType&quot;: &quot;MetaDataPropertyType&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;description&quot;,
        ///                    &quot;dataType&quot;: &quot;StringOrRefType&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;descriptionReference&quot;,
        ///                    &quot;dataType&quot;: &quot;ReferenceTyp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aaaNeu {
            get {
                return ResourceManager.GetString("aaaNeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;xPlan&quot;,
        ///    &quot;meta&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;XP_BegruendungAbschnitt&quot;,
        ///            &quot;description&quot;: &quot;Ein Abschnitt der Begr\u00fcndung des Plans.&quot;,
        ///            &quot;properties&quot;: [
        ///                {
        ///                    &quot;name&quot;: &quot;description&quot;,
        ///                    &quot;dataType&quot;: &quot;string&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;schluessel&quot;,
        ///                    &quot;dataType&quot;: &quot;string&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;text&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xplan {
            get {
                return ResourceManager.GetString("xplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;ZukunftBauAsJSON v1&quot;,
        ///    &quot;description&quot;: &quot;JSON Struktur für ZukunftBau&quot;,
        ///    &quot;meta&quot;: [
        ///        {
        ///            &quot;id&quot;: &quot;&quot;,
        ///            &quot;name&quot;: &quot;Grundstück&quot;,
        ///            &quot;description&quot;: &quot;Grundstücksfläche&quot;,
        ///            &quot;propertySet&quot;: [
        ///			{
        ///                &quot;Name&quot;: &quot;BauantragGrundstück&quot;,
        ///                &quot;guid&quot;: &quot;&quot;,
        ///                &quot;properties&quot;: [
        ///                    {
        ///                        &quot;id&quot;: 1,
        ///                        &quot;name&quot;: &quot;IstGrundstücksfläche&quot;,
        ///                        &quot;dat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZukunftBauAsJSON {
            get {
                return ResourceManager.GetString("ZukunftBauAsJSON", resourceCulture);
            }
        }
    }
}
