// <auto-generated>
//     Diese Datei wurde automatisch mit T4 generiert.
//     Änderungen werden beim nächsten Generieren überschrieben.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//embed BimGisCad
using BimGisCad.Representation.Geometry;            //handle placement
using BimGisCad.Representation.Geometry.Elementary; //need to calc rotation

//embed Xbim                                    //below selected examples that show why these are included
using Xbim.Ifc;                                 //IfcStore
using Xbim.Ifc4.GeometryResource;               //IfcAxis2Placement3D
using Xbim.Ifc4.RepresentationResource;         //IfcGeometricRepresentationContext

//embed logging
using BIMGISInteropLibs.Logging;                                 //need for LogPair
using LogWriter = BIMGISInteropLibs.Logging.LogWriterIfcTerrain; //to set log messages

namespace BIMGISInteropLibs.IFC.Ifc4.LoGeoRef
{
    /// <summary>
    /// Class to create LoGeoRef40
    /// </summary>
    public static class Level40
    {
        /// <summary>
        /// Create IfcGeometricRepresContext
        /// </summary>
        /// <param name="model">store of whole ifc model</param>
        /// <param name="placement">input placement</param>
        public static IfcGeometricRepresentationContext Create(IfcStore model, Axis2Placement3D placement)
        {
            //start transaction
            using (var txn = model.BeginTransaction("Create Geometric Representation Context [LoGeoRef40]"))
            {
                //get entity
                var grc = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();

                //set World Coordinate System
                grc.WorldCoordinateSystem =                 
                
                //create IfcAxis2Placement3D
                model.Instances.New<IfcAxis2Placement3D>(p =>
                {
                    //create IfcCartesianPoint by setting x y z
                    p.Location = model.Instances.New<IfcCartesianPoint>(c => c.SetXYZ(placement.Location.X, placement.Location.Y, placement.Location.Z));
                    LogWriter.Add(LogType.verbose, "IfcCartesianPoint (Easting: " + p.Location.X + "; Northing: " + p.Location.Y + "; Height: " + p.Location.Z + ") set!");
                   
                    //create IfcDirection - Axis
                    p.Axis = model.Instances.New<IfcDirection>(a => a.SetXYZ(placement.Axis.X, placement.Axis.Y, placement.Axis.Z));
                    LogWriter.Add(LogType.verbose, "IfcDirection - Axis (Easting: " + p.Axis.X + "; Northing: " + p.Axis.Y + "; Height: " + p.Axis.Z + ") set!");
                });

                //set true north prepared for ifc file
                grc.TrueNorth = model.Instances.New<IfcDirection>(d => d.SetXYZ(placement.TrueNorth.X, placement.TrueNorth.Y, 0));
                LogWriter.Add(LogType.verbose, "IfcDirection - TrueNorth (Easting: " + placement.TrueNorth.X + "; Northing: " + placement.TrueNorth.Y + "; Height: " + 0.0 + ") set!");
                //commit otherwise need to roll back
                txn.Commit();
                return grc;
            }
        } 
    }
}
