<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug_All;Debug;Release</Configurations>
    <StartupObject />
    <ApplicationIcon>DD_BIM_ICON.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GDAL" />
    <PackageReference Include="GeoJSON.Net" />
    <PackageReference Include="IxMilia.Dxf" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="NetTopologySuite.IO.PostGis" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.NetTopologySuite" />
    <PackageReference Include="RestSharp" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Speckle.Triangle" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="Xbim.Common" />
    <PackageReference Include="Xbim.Ifc" />
    <PackageReference Include="Xbim.IO.Esent" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DD_BIM_ICON.ico" />
    <Content Include="DD_BIM_LOGO.ico" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="IFC\Ifc2x3\LoGeoRef\Level30.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level30.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc2x3\LoGeoRef\Level40.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level40.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc2x3\PropertySet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PropertySet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc2x3\ShapeRepresentation.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShapeRepresentation.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc2x3\ShellBasedSurfaceModel.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShellBasedSurfaceModel.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\GeometricCurveSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GeometricCurveSet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\LoGeoRef\Level30.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level30.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\LoGeoRef\Level40.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level40.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\LoGeoRef\Level50.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level50.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\PropertySet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PropertySet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\ShapeRepresentation.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShapeRepresentation.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\ShellBasedSurfaceModel.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShellBasedSurfaceModel.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\Site.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Site.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\Store.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Store.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\Terrain.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Terrain.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\TriangulatedFaceSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedFaceSet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4dot3\TriangulatedIrregularNetwork.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedIrregularNetwork.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\GeometricCurveSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GeometricCurveSet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\LoGeoRef\Level30.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level30.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\LoGeoRef\Level40.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level40.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\LoGeoRef\Level50.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level50.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\PropertySet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PropertySet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\ShapeRepresentation.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShapeRepresentation.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\ShellBasedSurfaceModel.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShellBasedSurfaceModel.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\Site.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Site.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\Store.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Store.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\Terrain.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Terrain.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\TriangulatedFaceSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedFaceSet.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\Ifc4\TriangulatedIrregularNetwork.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedIrregularNetwork.tt</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\GeometricCurveSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GeometricCurveSet.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\Level40.cs">
      <DependentUpon>Level40.ttinclude</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="IFC\T4_Includes\Level30.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Level30.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\Site.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Site.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\Level50.cs">
      <DependentUpon>Level50.ttinclude</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="IFC\T4_Includes\InitModel.cs">
      <DependentUpon>InitModel.ttinclude</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="IFC\T4_Includes\PropertySet.cs">
      <DependentUpon>PropertySet.ttinclude</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="IFC\T4_Includes\Store.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Store.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\Terrain.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Terrain.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\ShellBasedSurfaceModel.cs">
      <DependentUpon>ShellBasedSurfaceModel.ttinclude</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="IFC\T4_Includes\ShapeRepresentation.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShapeRepresentation.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\TriangulatedFaceSet.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedFaceSet.ttinclude</DependentUpon>
    </Compile>
    <Compile Update="IFC\T4_Includes\TriangulatedIrregularNetwork.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TriangulatedIrregularNetwork.ttinclude</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="IFC\Ifc2x3\LoGeoRef\Level30.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level30.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc2x3\LoGeoRef\Level40.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level40.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc2x3\PropertySet.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>PropertySet.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc2x3\ShapeRepresentation.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ShapeRepresentation.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\GeometricCurveSet.tt">
      <LastGenOutput>GeometricCurveSet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4dot3\LoGeoRef\Level30.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level30.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\LoGeoRef\Level40.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level40.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\LoGeoRef\Level50.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level50.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\PropertySet.tt">
      <LastGenOutput>PropertySet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4dot3\ShellBasedSurfaceModel.tt">
      <LastGenOutput>ShellBasedSurfaceModel.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4dot3\ShapeRepresentation.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ShapeRepresentation.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\Site.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Site.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\Store.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Store.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\Terrain.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Terrain.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4dot3\TriangulatedFaceSet.tt">
      <LastGenOutput>TriangulatedFaceSet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4dot3\TriangulatedIrregularNetwork.tt">
      <LastGenOutput>TriangulatedIrregularNetwork.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\LoGeoRef\Level30.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level30.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\LoGeoRef\Level40.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level40.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\LoGeoRef\Level50.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Level50.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\PropertySet.tt">
      <LastGenOutput>PropertySet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\ShapeRepresentation.tt">
      <LastGenOutput>ShapeRepresentation.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\ShellBasedSurfaceModel.tt">
      <LastGenOutput>ShellBasedSurfaceModel.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\GeometricCurveSet.tt">
      <LastGenOutput>GeometricCurveSet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\Site.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Site.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\Store.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Store.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\Terrain.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Terrain.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc4\TriangulatedFaceSet.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TriangulatedFaceSet.cs</LastGenOutput>
    </None>
    <None Update="IFC\Ifc2x3\ShellBasedSurfaceModel.tt">
      <LastGenOutput>ShellBasedSurfaceModel.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\Ifc4\TriangulatedIrregularNetwork.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TriangulatedIrregularNetwork.cs</LastGenOutput>
    </None>
    <None Update="IFC\T4_Includes\Level40.ttinclude">
      <LastGenOutput>Level40.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\Level30.ttinclude">
      <LastGenOutput>Level30.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\Terrain.ttinclude">
      <LastGenOutput>Terrain.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\Store.ttinclude">
      <LastGenOutput>Store.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\Site.ttinclude">
      <LastGenOutput>Site.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\Level50.ttinclude">
      <LastGenOutput>Level50.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\PropertySet.ttinclude">
      <LastGenOutput>PropertySet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\GeometricCurveSet.ttinclude">
      <LastGenOutput>GeometricCurveSet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\TriangulatedIrregularNetwork.ttinclude">
      <LastGenOutput>TriangulatedIrregularNetwork.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\TriangulatedFaceSet.ttinclude">
      <LastGenOutput>TriangulatedFaceSet.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\ShellBasedSurfaceModel.ttinclude">
      <LastGenOutput>ShellBasedSurfaceModel.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="IFC\T4_Includes\ShapeRepresentation.ttinclude">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ShapeRepresentation.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <!-- MSBuild-Target: kopiert native libs aus GDAL.Native / gdal.native Paketen in Output -->
  <Target Name="CopyGdalNativeLibraries" AfterTargets="Build">
    <ItemGroup>
      <!-- versuche mehrere Paket-Id-Varianten (Groß-/Kleinschreibung / Namen möglich) -->
      <_GdalNativeFiles Include="$(NuGetPackageRoot)GDAL.Native*\runtimes\win-x64\native\**\*.*" />
      <_GdalNativeFiles Include="$(NuGetPackageRoot)gdal.native*\runtimes\win-x64\native\**\*.*" />
      <_GdalNativeFiles Include="$(NuGetPackageRoot)gdal.*\runtimes\win-x64\native\**\*.*" />
    </ItemGroup>

    <Message Importance="High" Text="Copying GDAL native files: '@(_GdalNativeFiles)' to $(OutputPath)" Condition="'@(_GdalNativeFiles)' != ''" />

    <Copy SourceFiles="@(_GdalNativeFiles)" DestinationFolder="$(OutputPath)%(RecursiveDir)" SkipUnchangedFiles="true" ContinueOnError="false" />
  </Target>
</Project>