<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug_All;Debug;Release</Configurations>
    <StartupObject />
    <ApplicationIcon>DD_BIM_ICON.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GDAL" />
    <PackageReference Include="GDAL.Native" />
    <PackageReference Include="GeoJSON.Net" />
    <PackageReference Include="IxMilia.Dxf" />
    <PackageReference Include="ManagedEsent" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Primitives" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="netDxf" />
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NetTopologySuite.Features" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" />
    <PackageReference Include="NetTopologySuite.IO.PostGis" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.LegacyPostgis" />
    <PackageReference Include="Npgsql.NetTopologySuite" />
    <PackageReference Include="RestSharp" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="System.Text.Encodings.Web" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="Xbim.Common" />
    <PackageReference Include="Xbim.Essentials" />
    <PackageReference Include="Xbim.Ifc" />
    <PackageReference Include="Xbim.Ifc2x3" />
    <PackageReference Include="Xbim.Ifc4" />
    <PackageReference Include="Xbim.IO.Esent" />
    <PackageReference Include="Xbim.IO.MemoryModel" />
    <PackageReference Include="Xbim.Tessellator" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.ServiceModel.Primitives" />
    <PackageReference Include="System.ServiceModel.Http" />
    <PackageReference Include="System.ServiceModel.Duplex" />
    <PackageReference Include="System.ServiceModel.NetTcp" />
    <PackageReference Include="System.ServiceModel.Security" />
    <PackageReference Include="System.ServiceModel.Federation" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DD_BIM_ICON.ico" />
    <Content Include="DD_BIM_LOGO.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BimGisCad\BimGisCad.csproj" />
  </ItemGroup>
</Project>